version: '2.3'
services:
  nginx:
    build: ./nginx
    networks:
      - front
      - back
    ports:
      - "80:80"
    volumes_from:
      - "daphne"
    depends_on:
      - daphne
    links:
      - daphne

  redis:
    image: redis
    networks:
      - "back"
    ports:
      - "6379:6379"
  
  daphne:
    build: .
    image: "myproject:latest"
    working_dir: /opt/discord
    command: bash -c "daphne -b 0.0.0.0 -p 8000 --proxy-headers core.asgi:application"
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - DJANGO_SETTINGS_MODULE=core.settings
    networks:
      - front
      - back
    depends_on:
      - redis
    links:
      - redis
networks:
  front:
  back:

