# Generated by Django 4.2 on 2023-04-21 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='server_list',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
