# Generated by Django 4.2 on 2023-05-01 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_server_list_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='server_list',
        ),
    ]
