# Generated by Django 4.2 on 2023-04-21 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='photo',
            field=models.ImageField(default='default.jpeg', upload_to='server/'),
        ),
    ]
