# Generated by Django 4.2 on 2023-04-22 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_server_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='channels',
            name='icon',
            field=models.CharField(default='static/images/iconsCH', max_length=1000),
        ),
    ]
