# Generated by Django 4.2 on 2023-04-22 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0003_channels_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channels',
            name='icon',
            field=models.CharField(default='static/images/iconsCH/hastag.png', max_length=1000),
        ),
    ]
