# Generated by Django 4.2 on 2023-04-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('id_to_server', models.IntegerField()),
                ('icon', models.CharField(default='static/images/iconsCH/hastag.png', max_length=1000)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(default='default.jpeg', upload_to='server/')),
            ],
        ),
    ]
