# Generated by Django 4.2 on 2023-04-29 21:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('id_to_server', models.IntegerField()),
                ('icon', models.CharField(default='static/images/iconsCH/hastag.png', max_length=1000)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('id_to_channel', models.IntegerField()),
                ('content', models.CharField(max_length=500)),
                ('user', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(default='default.jpeg', upload_to='server/')),
            ],
        ),
    ]
