# Generated by Django 4.2 on 2023-05-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_server_user_in_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='user_in_server',
            field=models.CharField(default='{"users": []}', max_length=300),
        ),
    ]
